# Generated by Django 3.2 on 2022-11-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ebook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('fantasy', 'Fantasy'), ('literary', 'Literary'), ('mystery', 'Mystery'), ('non_fiction', 'Non-Fiction'), ('Science_fiction', 'Science-Fiction'), ('thriller', 'Thriller')], max_length=100)),
                ('review', models.IntegerField()),
                ('favourite', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
