# Generated by Django 3.2 on 2022-11-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_ebook_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
