# Generated by Django 3.2 on 2022-11-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_users_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
