# Generated by Django 3.2 on 2023-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Literary', 'Literary'), ('Mystery', 'Mystery'), ('Non_Fiction', 'Non-Fiction'), ('Science_Fiction', 'Science-Fiction'), ('Thriller', 'Thriller')], max_length=100),
        ),
    ]
